package pl.lodz.p.samoyed.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.List;

@DynamoDBTable(tableName="SolvedTests")
public class SolvedTest {

    private String id;
    private String solvedBy;
    private Long solvedOn;
    private List<TestContent> versions;
    private String testId;

    @DynamoDBHashKey(attributeName="id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName="solvedBy")
    public String getSolvedBy() {
        return solvedBy;
    }
    public void setSolvedBy(String solvedBy) {
        this.solvedBy = solvedBy;
    }

    @DynamoDBAttribute(attributeName="solvedOn")
    public Long getSolvedOn() {
        return solvedOn;
    }
    public void setSolvedOn(Long solvedOn) {
        this.solvedOn = solvedOn;
    }

    @DynamoDBAttribute(attributeName="versions")
    public List<TestContent> getVersions() {
        return versions;
    }
    public void setVersions(List<TestContent> versions) {
        this.versions = versions;
    }

    @DynamoDBAttribute(attributeName="testId")
    public String getTestId() {
        return testId;
    }
    public void setTestId(String testId) {
        this.testId = testId;
    }

}
