package pl.lodz.p.samoyed.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.List;

@DynamoDBTable(tableName="Tests")
public class Test {

    private String id;
    private String author;
    private String title;
    private Long createdOn;
    private List<Question> questions;

    @DynamoDBHashKey(attributeName="Id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName="Author")
    public String getAuthor() {
        return author;
    }
    public void setAuthor(String author) {
        this.author = author;
    }

    @DynamoDBAttribute(attributeName="Title")
    public String getTitle() {
        return title;
    }
    public void setTitle(String title) {
        this.title = title;
    }

    @DynamoDBAttribute(attributeName="CreatedOn")
    public Long getCreatedOn() {
        return createdOn;
    }
    public void setCreatedOn(Long createdOn) {
        this.createdOn = createdOn;
    }

    @DynamoDBAttribute(attributeName="Questions")
    public List<Question> getQuestions() {
        return questions;
    }
    public void setQuestions(List<Question> questions) {
        this.questions = questions;
    }
}
