package pl.lodz.p.samoyed.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.List;

@DynamoDBTable(tableName="Tests")
public class Test {

    private String id;
    private String author;
    private Long createdOn;
    private List<TestContent> versions;
    private List<Assignment> assignments;

    @DynamoDBHashKey(attributeName="Id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName="Author")
    public String getAuthor() {
        return author;
    }
    public void setAuthor(String author) {
        this.author = author;
    }

    @DynamoDBAttribute(attributeName="CreatedOn")
    public Long getCreatedOn() {
        return createdOn;
    }
    public void setCreatedOn(Long createdOn) {
        this.createdOn = createdOn;
    }

    @DynamoDBAttribute(attributeName="Versions")
    public List<TestContent> getVersions() {
        return versions;
    }
    public void setVersions(List<TestContent> versions) {
        this.versions = versions;
    }

    @DynamoDBAttribute(attributeName="Assignments")
    public List<Assignment> getAssignments() {
        return assignments;
    }
    public void setAssignments(List<Assignment> assignments) {
        this.assignments = assignments;
    }

}
